spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shengong?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: dev_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.shengong: DEBUG
    dev.langchain4j: DEBUG
